osclass/Osclass

oc-includes/osclass/model/Alerts.php

I find a bug
I removed this line : $this->dao->groupBy('s_search'); because this function is to find each users with the same search. With a group by, I will always have one user. It's not meant to be like that.
Thanks!

BUG find Users By Search And Type

---

oc-includes/osclass/classes/ImageResizer.php

Alt solution for large PNG files with imagick (excessive 16 bit/ch bit depth).
Optionally it can be wrapped with if construct for png, but since jpegs are already at 8 bit, not really needed.

set image bit depth

---

oc-admin/themes/modern/users/ban_frm.php
oc-content/languages/en_US/core.po

If we want to block [1] just a root email domain, [2] single email subdomain or [3] entire email domain including all subdomains these are the proper wildcard examples.

Add additional ban rule example

---

oc-includes/osclass/Logger/LogDatabase.php

by adding a unique row identifier / descriptive name before timestamp we can quickly examine all rows w/ slow queries at once, instead of using regex to locate them

insert QUERY TIME descriptive name before query duration time

---

oc-admin/themes/modern/functions.php

This HTML comments hide some dots after ending just before next opening of php tags, which in some cases can produce weird errors like upon plugin installation (nothing harmful, but...).
Also, exiting from PHP just to insert HTML comment is not necessary.

some HTML cleanup

---

oc-includes/osclass/helpers/hDefines.php

Add missing helper osc_is_register_page()
Rename osc_is_login_fom() to osc_is_login_page() to keep consistency of function names
Pass osc_is_login_form() @deprecated

Add missing helper osc_is_register_page(), rename osc_is_login_form()

---

oc-includes/osclass/controller/login.php

http://forums.osclass.org/general-help/space-behind-login-email-user-does-not-exist/

trim email

---

oc-includes/osclass/classes/Plugins.php

There is no catching for exceptions on loading the plugin files.
Error handling is manage by 
```PHP
return array('error_code' => 'error_output', 'output' => ob_get_clean());
```
Regular errors will still be handled that way.
Exceptions will be displayed nicely.

Catch exceptions when loading plugin files

---

oc-includes/osclass/helpers/hItems.php

The word "formatted" is spelled incorrectly in `hItems.php`. This PR fixes it, but leaves the old function signature available.
Documentation should also be updated [here](https://doc.osclass.org/HItems.php)

fix spelling of "formatted"

---

oc-includes/osclass/ItemActions.php

This modification avoid a lot of allocated memory problem.
I don't create two object with my original image store in memory but only one object with my original picture in memory.
This allow on our website to upload an image of 5600x3000px.
Before I wasn't able to upload an image of 3800x2000px

Huge image process optimization (avoid allocated memory problem)

---

oc-includes/osclass/classes/ImageResizer.php

Sometimes we have this error on some production environment and not with all images...
exif_read_data(...): Illegal IFD size
Fix with a simple @.
http://stackoverflow.com/questions/5184748/php-bad-exif-data-warnings-what-to-do
Maybe

Fix Warning: exif_read_data(...): Illegal IFD size

---

oc-includes/osclass/cron.php

Hi, after some checks on some of my dev and production servers, I've noticed that certain very very old temp qqfiles are never removed. Their modified date is several months old, so by all reasoning, they should all met 2*3600 condition and be removed long time ago. Yet, it never happens.
Simple test `time()-filectime()` revealed puzzling thing at first - that `filectime()` [and consequently, time difference] resets every full hour, so that condition in cron cannot ever be reached, leaving this orphaned files forever to reside on the server.
Then I recalled that I run a custom shell script on all my servers that every full hour changes/resets owners/perms of public dirs and files to make sure they are ok, in case I change things as root or temporarily play with rwx bits. Every time this …

cron fix & refact

---

oc-includes/osclass/core/Params.php

When adding or editing items, ``Params::getFiles()`` method return a empty string when no files are added, causing a ``Fatal error: Cannot use string offset as an array in ...`` when files are uploaded with ajax.
This PR update the above method to return a empty array and solve the issue.

[hotfixes] Solve fatal error with Params::getFiles() method

---

oc-includes/osclass/core/Session.php

/ Do not try to start new session, if already started. /
Hi, I am using an auto-prepend script before Osclass runs, and I need to store some things into session for proper operation. Without this modification trying to start new session when it is already started will generate a lot of notices in the logs with each new request. I know that I can disable auto session start in .ini, but it is easier this way.
Thanks

session_start() fix

---

oc-includes/osclass/model/Log.php

In `oc_t_log`, the `s_ip` column is `NOT NULL`
When PHP is running from the command-line, `$_SERVER` is null, then it's impossible to insert logs from cron jobs.
``` php
if (!isset($_SERVER) || (isset($_SERVER) && !isset($_SERVER['REMOTE_ADDR']))) {
// CRON.
$_SERVER['REMOTE_ADDR']= '127.0.0.1';
}
```
It may be wise to switch the `s_ip` to `NULL` and make the update in the next release, don't know what's the method you prefer.

Log: allow cron to insert logs in oc_t_log table

---

oc-includes/osclass/model/Item.php

Fix bug if you have more than one category description.
The SUM is multiplied by the number of category description because here we use a simple FROM and not a JOIN.
By exemple if I have 3 languages and 3 category descriptions (One for each language) my result for the number or view and spam of an item will be multiplied by 3.

Fix bug on extendData

---

oc-includes/osclass/model/Region.php

Fix to remove an ambiguous column name in ajax request for regions

Ambiguous column name in Region fro ajax request

---

oc-includes/osclass/model/Search.php

If _conditions isn't called in makeSQLPremium users aren't able to filter premium sql request on Location or Category. 
It's because _conditions set withCategoryId and withLocations variable.

Small fix to be able to add category or a location

---

oc-admin/themes/modern/less/sidebar.less

This little change allow the scroll for other submenu.
Useful if a plugin add a new section with too many link in the submenu.

Allow scroll y for all submenu and not only menu_plugins

---

oc-includes/osclass/core/View.php

Current View::_current() method only supports looping over arrays of arrays.
We often export lists (arrays) of objects like in our messenger plugin.
For example, our exported `mdh_messages` variables looks like that :
```
Array(
[0] => Madhouse_Messenger_Message (object)
[1] => Madhouse_Messenger_Message (object)
[2] => Madhouse_Messenger_Message (object)
)
```
We had to make a fix because of the `is_array($this->aCurrent[$key])` condition in the current code :
``` PHP
function _current($key)
{
if ( isset($this->aCurrent[$key]) && is_array($this->aCurrent[$key]) ) {
return $this->aCurrent[$key];
} elseif ( is_array($this->aExported[$key]) ) {
$this->aCurrent[$key] = current( $this->aExported[$key] );
return $this->aCurrent[$key];
}
return '';
}
```
This fix enables looping around arrays …

Make View::_current() support for looping on array of anything

---

oc-includes/osclass/controller/search.php

Hi,
Just an idea but so useful for plugins. <3
If found this line on item controller :
``` PHP
$item = osc_apply_filter('pre_show_item', $this->itemManager->findByPrimaryKey( Params::getParam('id') ));
```
And it's perfect to complete an item with data from plugins with array_merge.  After this I create an helper in my plugin who use osc_item_field('plugin_filed', locale).
This new line will allow users to use plugins helpers to display new informations on search.
If you like this we can add this line wherever an array of item is exported. And add the line pre_show_item wherever an item is exported.
Regards

Add filter in search to add data from plugins to items

---

oc-includes/osclass/helpers/hDefines.php

Child themes can't work properly if the files missing in the child theme aren't loaded with the parent. 
Fix osc_current_web_theme_url()

Fix url bug with child-themes

---

oc-includes/osclass/UserActions.php
oc-includes/osclass/helpers/hUtils.php

The password recovery page only shows a recaptcha if a previous recovery has been made within the past two minutes. But the backend logic checks the recaptcha even when one hasn't been shown meaning that password reset requests fail. This pull request sets a server side session variable which bypasses the recaptcha check if one wasn't shown in the form.

Fixes recaptcha checking in password recovery. 
