osclass/Osclass

oc-includes/osclass/utils.php
=> trim unnecessary blank lines

oc-admin/themes/modern/categories/iframe.php
=> comment translation

oc-includes/osclass/controller/ajax.php, oc-includes/osclass/controller/contact.php, oc-includes/osclass/controller/custom.php, oc-includes/osclass/controller/item.php, oc-includes/osclass/controller/language.php, oc-includes/osclass/controller/login.php, oc-includes/osclass/controller/main.php, oc-includes/osclass/controller/page.php, oc-includes/osclass/controller/register.php, oc-includes/osclass/controller/user-non-secure.php, oc-includes/osclass/controller/user.php
=> Hooks per controller

oc-admin/themes/modern/market/section.php
=> message typo

oc-includes/osclass/classes/Plugins.php
I am not 100% sure about this, for example before_ hooks might be redundant in a way, but I added them for symmetry. Any thoughts are welcome.
Thanks
=> Plugins Action Hooks

oc-admin/themes/modern/items/index.php, oc-includes/osclass/classes/AdminMenu.php
both strings exists so no need to update core.po except referencing files/numbers might be wrong
=> fix issue #1852

oc-includes/osclass/helpers/hItems.php
breaks W3C but I don't see any other way to make this work...
=> fix #1928 (hotfix branch)

oc-content/languages/en_US/core.po, oc-includes/osclass/model/Category.php
#1981
actually this is better.
=> fix notice

oc-includes/osclass/cron.php
=> fix issue #2007

oc-admin/themes/modern/settings/index.php, oc-content/languages/en_US/core.po
=> Mislabeled Contact e-mail

oc-admin/gui/forgot_password.php, oc-admin/gui/login.php, oc-admin/gui/recover.php
add focus, remove tabindexes, some code reformat
=> UI improvements

oc-includes/osclass/Themes.php
unify filter with /classes/Scripts.php class
=> theme scripts path filter

oc-includes/osclass/UserActions.php
=> log improvement

oc-includes/osclass/functions.php
fix by SmaRTeY:
http://forums.osclass.org/3-6-x/possible-footer-links-url-fix/
=> osc_footer_link_url() fix

oc-includes/osclass/controller/user.php
=> before_user_delete hook

oc-admin/gui/recover.php
=> add missing form name/id

oc-includes/osclass/helpers/hItems.php
=> resource filters

oc-includes/osclass/controller/item.php
When possible, let's Preserve original i18n translation
++
Changed osc_add_flash_error_message TO osc_add_flash_warning_message
=> Preserve original i18n translation

oc-admin/gui/forgot_password.php, oc-admin/gui/login.php, oc-admin/gui/recover.php
=> admin login footer hooks

oc-includes/osclass/controller/user-non-secure.php
Add new hook 'change_email_confirm' with params:
Id user
Old email => (We're working on an Mailchimp plugin and we need to unsubsribe the old email when user change his email)
New email
=> Add new hook 'change_email_confirm'

oc-includes/osclass/frm/Item.form.class.php
There is just one thing I couldn't figure out. How can we pass or capture category ID (via ajax) to restrict where it will be shown. Could be done inside plugin, though.
Thanks
=> Support for custom validation rules/messages

oc-includes/osclass/controller/item.php
=> pre item comment hooks

oc-includes/osclass/core/Cookie.php
Not sure why substr() is used, to save some bits maybe?
=> remove substr + minor format

oc-includes/osclass/helpers/hSecurity.php
fix descriptions + formatting
https://github.com/osclass/Osclass/commit/badc507e4b14e659466113970f78e97a83b1886f
=> fix descriptions + formatting

oc-includes/osclass/upgrade-funcs.php
=> recaptcha preference section upgrade fix

oc-includes/osclass/classes/AdminMenu.php
=> Manage Menu reorder

oc-includes/osclass/compatibility.php
=> fix typo #1893

oc-includes/osclass/controller/contact.php, oc-includes/osclass/emails.php
#1979 contact email account used for admin notifications
=> fix issue #1979 emails

oc-includes/osclass/functions.php
=> Add route title to meta title

oc-includes/osclass/helpers/hUsers.php
=> new filter

oc-includes/osclass/controller/search.php, oc-includes/osclass/helpers/hSearch.php
Not sure about https://github.com/osclass/Osclass/blob/develop/oc-includes/osclass/helpers/hSearch.php#L128, from early tests it's not required.
=> search filter

oc-includes/osclass/helpers/hPreference.php
fix #2266 PHP Warning: A non-numeric value(s) + minor code formatting
=> fix #2266 PHP Warning: A non-numeric value(s) + minor code formatting [2nd try]
